# Çiftçinin ayarları
Settings:
   # Claimlere özel çiftçi konması sağlanır.
   # Sonradan açılamaz çiftçi verilerinin SIFIRLANMASI GEREKİR!
   # /çiftçi reload ile değişmez hata verir kapatıp açılması gereklidir.
   useClaims: false
   # Çiftçinin çalışması için ada üyelerinden birisinin
   # Çevrim içi olması gereksin mi?
   requireOnline: false
   # Çiftçinin seviyesini yumurta üzerinden işler!
   # DIKKAT Bunun için lang.yml'de çiftçinin yumurta adında
   # {level} placeholderını kullanmanız gerekli! Kullanmazsanız
   # Eklenti düzgün çalışmaz!
   levelBasedFarmer: false
   # Oyuncunun yere attığı ürünleri çiftçi toplasın mı toplamasın mı ayarıdır.
   # true yapılırsa çiftçi oyuncu tarafından atılan ürünleri envanterine almaz.
   # false yapılırsa çiftçi oyuncu tarafından atılan ürünleri de toplar.
   playerDropCancel: false
   # Çiftçi menüsüne erişim sadece lidere mi olsun ayarıdır.
   onlyLeader: false
   # Çiftçinin çalışacağı dünyalar.
   defaultWorld:
   - ASkyBlock
   - ASkyBlock_nether
   # Çiftçiyi parayla alabilir mi?
   buyFarmer:
      feature: false
      price: 30000
   # Ürün satılınca para kime yatırılacak ayarları.
   depositMethod:
      # Lider kime yatırılacağını seçebilsin. (Satan kişiye veya Lidere)
      leaderChoose: true
      # Varsayılan olarak parayı lidere yatır.
      defaultDepositLeader: false

AddonSettings:
   # Çiftçinin çalışabileceği dünyaların listesi aşağıdadır.
   # Örneğin skyblock eklentileri sadece kendi dünyalarında çalışır.
   # Onların dünyasını aşağı yazın kapatmak isterseniz aşağıdan gerekli dünyaları silin.
   # Çiftçinin stok dolduğunda oto satış yapma özelliğini açar.
   # Yetkisi: ciftci.autosell
   autoSell:
      feature: true
      sendMessage: true
   # Spawnerların otomatik öldürülmesi ayarıdır.
   # Yetkisi: ciftci.spawnerkill
   spawnerKiller:
      withoutFarmer: false
      toggle: true
      cookFoods: true
      blacklist:
      - VILLAGER
   # Performansı direkt olarak etkileyebilecek bir ayardır.
   # Açılması yeterli değildir Items.yml'den de ayarlanması gerekir.
   # BETA aşamasındadır. Kullanımı riskleri kabul ederek açın.
   # Yetkisi: ciftci.autocollect
   autoCollect:
      feature: true
      withoutFarmer: false
      toggle: true
      requirePiston: false
      ignoreStock: true

# Vergi ayarları:
tax:
   # Vergi ayarlarıdır. (0 yazarak devre dışı bırakılabilir.)
   taxRate: 10
   # Vergi bir hesaba yatırılsın mı? Yoksa sadece oyuncuya eksik para mı verilsin?
   depositToAcc: false
   # Verginin yatırılacağı oyuncu.
   taxAcc: Geyik

# Detaylı ayarlardır. Bilginiz yoksa lütfen ellemeyin.
DetailedSettings:
   # NPC'leri sync olarak koyup geri alır.
   # Açılırsa async olarak bu işlemi yapar. Lag anında
   # veya kötü performans anında npcler ara sıra görünmeyebilir.
   # 15 blok uzaklaşılıp geri girildiğinde tekrar çalışır.
   asyncNPC: false
   # /çiftçi shutdown komutu ile bütün çiftçileri durdurur.
   # Çiftçinin hiç bir işlevi çalışmaz.
   # Bu ayar ise default durumunu belirler
   shutDown: false
   # Spawner Öldürücü doğan mobu öldürdüğünde
   # Ölme animasyonu olsun mu olmasın mı
   # (Yaratığın hasar yiyip ölme animasyonu)
   removeMob: true
   # Eşyayı alırken vergi keserek eksik item verir.
   taxOnTake: false
   # Sadece oyuncunun sahip olduğu çiftçileri tarar
   scanOnlyAdded: false
   
      
# Çiftçi seviye ayarları:
# İstenildiği kadar seviye eklenebilir.
# Metod kopyalanarak 1-2-3-4-....-x şeklinde uzatılabilir.
# Değişkenler:
# taxRate: seviyeye özel vergi oranı
# permission: buraya seviye atlanması için istediğiniz permi yazın.
FarmerLevels:
   1:
     # Çiftçinin mevcut kapasitesini belirler.
     Capacity: 1000
     # Sıradaki aşama için gerekli parayı belirler. Son seviye için girilmesine gerek yoktur.
     nextRankMoney: 5000
   2:
     Capacity: 3000
     nextRankMoney: 10000
     taxRate: 7
   3:
     Capacity: 10000
     permission: ciftci.vip
     taxRate: 5