settings:
  # if you want to enable it, set this to true
  # this setting will enable the auto-seller
  feature: false
  # if you want to enable the auto-seller for all players, set this to true
  # if you want to enable the auto-seller for specific players, set this to false (perm-check)
  defaultStatus: false
  # custom perm only used if defaultStatus is false
  # only players with this perm will be able to use the auto-seller
  customPerm: "farmer.autoseller"
  # all the items that will be sold by the auto-seller
  # you can add as many items as you want
  # the items must be same as the ones in the items.yml of the Farmer
  # you can also remove this section for enable it to all items
  items:
    - PUMPKIN
    - MELON
    - WHEAT
    - CACTUS